

//AUTH
  export const AUTH_START = 'AUTH_START';

  export const AUTH_LOGOUT = 'AUTH_LOGOUT';

  export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
  export const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL';

  export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS';
  export const AUTH_SIGNIN_FAIL = 'AUTH_SIGNIN_FAIL';
  
  export const AUTH_CLEAR_SIGNUP_REDIRECT = 'AUTH_CLEAR_SIGNUP_REDIRECT';
  export const AUTH_CLEAR_SIGNIN_REDIRECT = 'AUTH_CLEAR_SIGNIN_REDIRECT';

  export const AUTH_STORE_USER = 'AUTH_STORE_USER';
  